// <auto-generated />
using System;
using Day04Lab.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Day04Lab.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Day04Lab.Models.Categories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Dry Groceries"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dairy & Eggs"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Meat & Frozen Food"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Canned Goods"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Beverages"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Snacks & Sweets"
                        });
                });

            modelBuilder.Entity("Day04Lab.Models.Products", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriesId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date_Of_Expire")
                        .HasColumnType("date");

                    b.Property<DateOnly>("Date_Of_Production")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriesId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriesId = 1,
                            Count = 150,
                            Date_Of_Expire = new DateOnly(2027, 1, 10),
                            Date_Of_Production = new DateOnly(2026, 1, 10),
                            Description = "High-quality natural white rice, 1kg pack",
                            Price = 35,
                            Title = "Premium Egyptian Rice"
                        },
                        new
                        {
                            Id = 2,
                            CategoriesId = 1,
                            Count = 200,
                            Date_Of_Expire = new DateOnly(2027, 2, 1),
                            Date_Of_Production = new DateOnly(2026, 2, 1),
                            Description = "Made from 100% pure durum wheat semolina, 400g",
                            Price = 15,
                            Title = "Penne Pasta"
                        },
                        new
                        {
                            Id = 3,
                            CategoriesId = 1,
                            Count = 80,
                            Date_Of_Expire = new DateOnly(2027, 1, 5),
                            Date_Of_Production = new DateOnly(2026, 1, 5),
                            Description = "Pure refined sunflower oil for cooking and frying, 1L",
                            Price = 80,
                            Title = "Sunflower Oil"
                        },
                        new
                        {
                            Id = 4,
                            CategoriesId = 2,
                            Count = 60,
                            Date_Of_Expire = new DateOnly(2026, 11, 1),
                            Date_Of_Production = new DateOnly(2026, 5, 1),
                            Description = "Pasteurized and sterilized natural cow milk, 1L",
                            Price = 42,
                            Title = "Full Cream Milk"
                        },
                        new
                        {
                            Id = 5,
                            CategoriesId = 2,
                            Count = 90,
                            Date_Of_Expire = new DateOnly(2026, 10, 15),
                            Date_Of_Production = new DateOnly(2026, 4, 15),
                            Description = "Smooth vegetable oil feta cheese, 500g",
                            Price = 38,
                            Title = "Feta White Cheese"
                        },
                        new
                        {
                            Id = 6,
                            CategoriesId = 2,
                            Count = 120,
                            Date_Of_Expire = new DateOnly(2026, 6, 4),
                            Date_Of_Production = new DateOnly(2026, 5, 20),
                            Description = "Fresh plain yogurt cup, 105g",
                            Price = 8,
                            Title = "Natural Yogurt"
                        },
                        new
                        {
                            Id = 7,
                            CategoriesId = 3,
                            Count = 45,
                            Date_Of_Expire = new DateOnly(2026, 9, 1),
                            Date_Of_Production = new DateOnly(2026, 3, 1),
                            Description = "Pure beef burger patties ready for grilling, 1kg",
                            Price = 160,
                            Title = "Frozen Beef Burger"
                        },
                        new
                        {
                            Id = 8,
                            CategoriesId = 3,
                            Count = 40,
                            Date_Of_Expire = new DateOnly(2026, 8, 20),
                            Date_Of_Production = new DateOnly(2026, 2, 20),
                            Description = "Breaded and seasoned chicken breast fillets, 1kg",
                            Price = 180,
                            Title = "Frozen Chicken Pane"
                        },
                        new
                        {
                            Id = 9,
                            CategoriesId = 4,
                            Count = 110,
                            Date_Of_Expire = new DateOnly(2027, 7, 15),
                            Date_Of_Production = new DateOnly(2026, 1, 15),
                            Description = "Natural rich tomato paste jar, 360g",
                            Price = 22,
                            Title = "Tomato Paste Puree"
                        },
                        new
                        {
                            Id = 10,
                            CategoriesId = 4,
                            Count = 130,
                            Date_Of_Expire = new DateOnly(2029, 1, 1),
                            Date_Of_Production = new DateOnly(2026, 1, 1),
                            Description = "Easy-open canned solid tuna in vegetable oil, 185g",
                            Price = 55,
                            Title = "Solid Tuna"
                        });
                });

            modelBuilder.Entity("Day04Lab.Models.Products", b =>
                {
                    b.HasOne("Day04Lab.Models.Categories", "Category")
                        .WithMany("Product")
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Day04Lab.Models.Categories", b =>
                {
                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
